version: '3.3'
services:


  postgres_backend_api:
    image: postgres:latest
    container_name: user-db
    env_file: .env
    ports:
      - 5432:5432

  pgAdmin:
    image: dpage/pgadmin4:latest
    container_name: pgAdmin
    depends_on:
      - postgres_backend_api
    ports:
      - 16555:80
    environment:
      PGADMIN_DEFAULT_EMAIL: gilyazovan97@mail.ru
      PGADMIN_DEFAULT_PASSWORD: password97
    logging:
      driver: none
